name: GitHub Actions Go Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19' ]
    name: Go ${{ matrix.go }} todo-api
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          run: |
            go get github.com/mingrammer/go-todo-rest-api-example
            go build -v ./...
            ./go-todo-rest-api-example

